apiVersion: apps/v1
kind: Deployment
metadata:
  name: glue-config
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: glue-config
  template:
    metadata:
      labels:
        app: glue-config
    spec:
      containers:
        - image: gcu-dudezi-dev.kr-central-2.kcr.dev/glue-repository/glue-config:e7e190de5f873138e549c02225b88e7f8c8c6ea9
          name: glue-config-server
          ports:
            - containerPort: 8888
      imagePullSecrets:
        - name: glue-repository
