server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: ${{ GIT_URI }}
          default-label: main
          username: ${{ GIT_USERNAME }}
          password: ${{ GIT_TOKEN }}
